name: Stanley-lua/oscapture
description: Capture commandline output.
version: 0.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload: 
  - type: global
    name: os.capture
    path: oscapture.lua
